# Disable unused ArgoCD controllers to save resources
# - notifications: Not using Slack/Discord alerts
# - applicationset: Not using ApplicationSet templates
# - dex: Using Authelia for SSO instead
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
  namespace: argocd
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
  namespace: argocd
spec:
  replicas: 0
