apiVersion: batch/v1
kind: Job
metadata:
  name: vault-populate-secrets
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault-config
      restartPolicy: OnFailure
      containers:
      - name: vault-populate
        image: hashicorp/vault:1.15
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          value: "root"
        command:
        - /bin/sh
        - -c
        - |
          set -e

          echo "Waiting for Vault to be ready..."
          until vault status; do
            echo "Vault not ready, waiting..."
            sleep 2
          done

          echo "Populating Vault secrets..."

          # PostgreSQL secrets
          echo "  - postgresql/root"
          vault kv put secret/postgresql/root \
            PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" \
            POSTGRES_PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" \
            REPLICATION_PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          # Gitea secrets
          echo "  - gitea/postgres"
          vault kv put secret/gitea/postgres \
            PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          echo "  - gitea/admin"
          vault kv put secret/gitea/admin \
            USERNAME="bluemayne" \
            PASSWORD="Gi87345364@"

          echo "  - gitea/minio"
          vault kv put secret/gitea/minio \
            ROOT_USER="gitea" \
            ROOT_PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          echo "  - gitea/runner"
          vault kv put secret/gitea/runner \
            TOKEN="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          # MinIO secrets
          echo "  - minio/root"
          vault kv put secret/minio/root \
            ROOT_USER="admin" \
            ROOT_PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          # Grafana secrets
          echo "  - monitoring/grafana"
          vault kv put secret/monitoring/grafana \
            ADMIN_USER="admin" \
            ADMIN_PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          # PostgreSQL monitoring
          echo "  - monitoring/postgresql"
          vault kv put secret/monitoring/postgresql \
            PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          # Umami analytics
          UMAMI_DB_PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
          echo "  - analytics/umami"
          vault kv put secret/analytics/umami \
            DATABASE_URL="postgresql://umami:${UMAMI_DB_PASSWORD}@postgresql.postgresql.svc.cluster.local:5432/umami" \
            HASH_SALT="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 64 | head -n 1)"

          # Code Server
          echo "  - dev-tools/code-server"
          vault kv put secret/dev-tools/code-server \
            PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          # PGWeb
          echo "  - tools/pgweb"
          vault kv put secret/tools/pgweb \
            DATABASE_URL="postgresql://bluemayne@postgresql.postgresql.svc.cluster.local:5432/postgres?sslmode=disable"

          # PostgreSQL Dev
          echo "  - postgresql-dev/root"
          vault kv put secret/postgresql-dev/root \
            PASSWORD="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

          echo ""
          echo "Secret population completed successfully!"

          echo ""
          echo "Listing all secrets:"
          vault kv list secret/ || true
