apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.9
    helm:
      values: |
        # Controller configuration
        controller:
          enabled: true
          image:
            repository: quay.io/metallb/controller
            tag: v0.14.9

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              # cpu: removed to prevent throttling
              memory: 128Mi

        # Speaker configuration (runs on each node)
        speaker:
          enabled: true
          image:
            repository: quay.io/metallb/speaker
            tag: v0.14.9

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              # cpu: removed to prevent throttling
              memory: 128Mi

          # Tolerations to run on all nodes
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane

          # Disable FRR in speaker (we use L2 mode, not BGP)
          frr:
            enabled: false

        # Disable FRR globally (only needed for BGP mode, we use L2)
        frr:
          enabled: false

        frrk8s:
          enabled: false

        # Prometheus metrics
        prometheus:
          scrapeAnnotations: true
          metricsPort: 7472

        # RBAC
        rbac:
          create: true

        # Service Accounts
        controller:
          serviceAccount:
            create: true
            name: metallb-controller

        speaker:
          serviceAccount:
            create: true
            name: metallb-speaker
  - repoURL: https://github.com/Mayne0213/cluster-infrastructure.git
    targetRevision: main
    path: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: 'true'
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jqPathExpressions:
    - .spec
    - .status
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgpadvertisements.metallb.io
    jqPathExpressions:
    - .spec
    - .status
  revisionHistoryLimit: 10
