apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    # IP range for LoadBalancer services
    # Adjust this range based on your network configuration
    - 10.0.0.100-10.0.0.120
  autoAssign: true
