apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: velero-s3-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .minioAccessKey }}
          aws_secret_access_key="{{ .minioSecretKey }}"

  data:
    - secretKey: minioAccessKey
      remoteRef:
        key: databases/minio
        property: ROOT_USER

    - secretKey: minioSecretKey
      remoteRef:
        key: databases/minio
        property: ROOT_PASSWORD
